import React from 'react';
import { Info } from 'lucide-react';

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-slate-50 pt-28 pb-16 px-4 sm:px-6">
      <div className="max-w-3xl mx-auto bg-white p-6 sm:p-10 rounded-[2rem] shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-slate-100">
        
        {/* Compact Header */}
        <div className="flex items-center gap-4 mb-8 border-b border-slate-100 pb-6">
          <div className="w-12 h-12 rounded-[1rem] bg-blue-50 text-blue-500 flex items-center justify-center shrink-0">
            <Info size={24} />
          </div>
          <h1 className="text-3xl sm:text-4xl font-black text-slate-900 tracking-tight">Disclaimer</h1>
        </div>
        
        {/* Content */}
        <div className="space-y-6 text-slate-600 text-sm sm:text-base font-medium leading-relaxed">
          <p>All the information and tools on Age Calculator Box are published in good faith and for general information and utility purposes only.</p>
          
          <h2 className="text-xl font-black text-slate-800 mt-8 mb-3">1. Tool Accuracy</h2>
          <p>While we have built our calculators to be as precise as possible, variations can occasionally occur due to leap years, timezone differences, or how different browsers handle dates. Therefore, we do not make any strict warranties about the 100% completeness or reliability of the results.</p>
          
          <h2 className="text-xl font-black text-slate-800 mt-8 mb-3">2. Not for Official Use</h2>
          <p>The results generated by our tools should not be used as a substitute for legal, medical, or official age verification. Always rely on government-issued IDs or official birth certificates for formal documentation.</p>

          <h2 className="text-xl font-black text-slate-800 mt-8 mb-3">3. External Links</h2>
          <p>Our website may contain links to external sites (like advertisement networks). While we strive to provide only quality links, we have no control over the content of these external websites and cannot be held responsible for them.</p>

          <p className="mt-8 font-bold text-slate-800">
            Any action you take upon the information you find on this website is strictly at your own risk.
          </p>
        </div>

      </div>
    </div>
  );
}